[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
itertools = "0.13.0"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"
